
version: '3.9'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./CREATE.sql:/docker-entrypoint-initdb.d/CREATE.sql
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: go_web
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: password
      DB_NAME: mydb
    ports:
      - "8080:8080"
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    environment:
      - TZ=Europe/Dublin # Change this to your timezone
      - TUNNEL_TOKEN=
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    network_mode: "host"                              # Use the host network (no isolation between host and container)

volumes:
  pgdata:


